jobs:
  - job:
    templateContext:
      outputs:
        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/dropOutput
          artifact: drop
          sbomBuildDropPath: '$(Build.ArtifactStagingDirectory)/dropInput'
          sbomPackageName: 'Azure Functions PowerShell OpenTelemetry SDK'
          sbomBuildComponentPath: '$(Build.SourcesDirectory)'
    steps:
      - pwsh: ./build.ps1 -Configuration "Release"
        displayName: "Running ./build.ps1 -Configuration 'Release'"

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(System.DefaultWorkingDirectory)/test/E2E/app/Modules"
          Contents: '**'
          TargetFolder: "$(Build.ArtifactStagingDirectory)/dropInput"
        displayName: "Copy package to artifacts directory"

      - pwsh: |
          mkdir $(Build.ArtifactStagingDirectory)/dropOutput -Force | Out-Null
          Compress-Archive -Path $(Build.ArtifactStagingDirectory)/dropInput/AzureFunctions.PowerShell.OpenTelemetry.SDK/* -DestinationPath $(Build.ArtifactStagingDirectory)/dropOutput/AzureFunctions.PowerShell.OpenTelemetry.SDK.zip
        displayName: "Zip Module"
