jobs:
  - job: UnitTests
    steps:
      - task: NuGetAuthenticate@1
        displayName: Authenticate to CFS

      - pwsh: ./build.ps1 -Configuration "Release"
        displayName: ./build.ps1 -Configuration "Release"

      - pwsh: ./build.ps1 -NoBuild -Test
        displayName: "Running UnitTest"
